plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.hilt)
    alias(libs.plugins.ksp)
}

android {
    namespace = "com.example.tenet"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.tenet"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    // jniLibs contains the compiled Rust .so files (generated by cargo-ndk,
    // git-ignored — see android/build.sh to build them).
    sourceSets["main"].jniLibs.srcDirs("src/main/jniLibs")

    // UniFFI-generated Kotlin bindings are placed here by uniffi-bindgen.
    sourceSets["main"].java.srcDirs(
        "src/main/java",
        "src/main/java/com/example/tenet/uniffi"
    )

    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "armeabi-v7a", "x86_64")
            isUniversalApk = false
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)

    // Compose BOM manages all compose library versions
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    debugImplementation(libs.androidx.ui.tooling)

    // Navigation
    implementation(libs.androidx.navigation.compose)

    // Hilt DI
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.hilt.navigation.compose)
    implementation(libs.hilt.work)
    ksp(libs.hilt.compiler.androidx)

    // WorkManager
    implementation(libs.androidx.work.runtime.ktx)

    // Image loading
    implementation(libs.coil.compose)

    // JNA — required by the UniFFI Kotlin runtime
    implementation("${libs.jna.get().module}:${libs.jna.get().version}@aar")

    // Coroutines
    implementation(libs.kotlinx.coroutines.android)

    // QR code — generation and scanning (ZXing Android Embedded bundles ZXing core)
    implementation(libs.zxing.android.embedded)

    // Unit testing
    testImplementation("junit:junit:4.13.2")
}
